export const achievements = [
  {
    title: 'Open Source Contributor',
    description: 'Contributed to Meshery by improving website features and fixed typos on the MUI documentation site.',
    date: '2023–2024',
    link: 'https://github.com/meshery/meshery.io/pull/1634',
    link1: 'https://github.com/mui/mui-x/pull/11967',
  },
  {
    title: 'Intern at DRDO',
    description: 'Selected for a 2-month internship at DRDO, contributing to high-impact research and development tasks.',
    date: 'Summer 2024',
    link: '#',
    link1: '#',
  },
  {
    title: 'Custom Portfolio for International Student',
    description: 'Created a responsive, visually appealing React-based portfolio for an international Ivy League applicant.',
    date: 'Feb 2023',
    link: '#',
    link1: '#',
  },
];

export const experiences = [
  {
    company: 'Epicenter (YC S25)',
    role: 'Open Source Maintainer (Sponsored)',
    period: 'Aug 2025 - Present',
    location: 'Remote',
    description: 'Selected as sponsored maintainer for YC-backed productivity platform through GitHub Sponsors program. Contribute to UI/UX and review community pull requests for growing global user base. Work with other maintainers on code reviews, bug fixes, and feature implementation.',
    technologies: ['UI/UX', 'Frontend Development', 'Code Review'],
  },
  {
    company: 'Userology',
    role: 'Software Engineer',
    period: 'Aug 2024 - Jan 2025',
    location: 'Remote',
    description: 'Developed secure authentication systems using Firebase and Next.js with optimized user experience. Enhanced WebRTC video call performance, improving connection stability and quality by 30%. Built responsive web applications from Figma designs using React, TypeScript, and modern CSS.',
    technologies: ['Next.js', 'Firebase', 'Tailwind CSS', 'WebRTC', 'TypeScript'],
  },
  {
    company: 'Freelance',
    role: 'Freelance Full-Stack Developer',
    period: 'Mar 2024 - Oct 2024',
    location: 'Remote',
    description: 'Developed conversational AI platform integrating OpenAI, D-ID, and ElevenLabs APIs. Built complete full-stack solution with React frontend, Node.js backend, and MongoDB database. Implemented secure payment processing and user authentication.',
    technologies: ['Node.js', 'MongoDB', 'Firebase', 'Twilio', 'React.js', 'REST APIs', 'Stripe'],
  },
  {
    company: 'VaySolar',
    role: 'Frontend Developer',
    period: 'Nov 2023 - May 2024',
    location: 'New Delhi, India',
    description: 'Built internal dashboards for operations, admin, and client teams using React and Material-UI. Integrated Swagger-documented REST APIs with optimized loading states, reducing wait times. Collaborated with product team on design reviews and improved workflow efficiency for internal teams.',
    technologies: ['React.js', 'Material-UI'],
  },
  {
    company: 'Frontend Mentor',
    role: 'Mentor (Volunteer)',
    period: 'Sep 2023 - Apr 2024',
    location: 'Remote',
    description: 'Reviewed 350+ user submissions, providing detailed feedback on HTML, CSS, JavaScript, and React projects. Helped developers improve frontend implementations and best practices. Earned multiple community badges (Mentor of the Week/Month).',
    technologies: ['Code Review', 'React.js', 'Responsive Web Design', 'CSS', 'JavaScript'],
  },
  {
    company: 'Decentraclasses',
    role: 'Frontend Developer',
    period: 'Oct 2023 - Feb 2024',
    location: 'Remote',
    description: 'Built the initial website of an early-stage EdTech startup using React and Tailwind CSS. Translated Figma designs into responsive, mobile-friendly pages. Added interactive animations and optimized load speed for a better UX.',
    technologies: ['React.js', 'Tailwind CSS'],
  },
  {
    company: 'Botter Solutions Pvt. Ltd.',
    role: 'Frontend Developer',
    period: 'Nov 2023 - Dec 2023',
    location: 'Remote',
    description: 'Developed UI for directional drilling software in the Oil & Gas sector using React and Material-UI. Built large Excel-style dataset views using MUI Data Grid with custom calculations. Improved data visualization and UX for engineers by integrating APIs and optimizing responsiveness.',
    technologies: ['React.js', 'Material-UI'],
  },
  {
    company: 'MyShop',
    role: 'React.js Developer',
    period: 'Aug 2022 - Sep 2022',
    location: 'Remote',
    description: 'Developed complete responsive website from Figma designs using React. Implemented custom animations and loading states for enhanced user experience. Ensured cross-browser compatibility and mobile responsiveness. First paid internship role, delivering production-ready web application.',
    technologies: ['React.js', 'EmailJS', 'CSS'],
  },
  {
    company: 'GirlScript Summer of Code',
    role: 'Contributor',
    period: 'Mar 2022 - May 2022',
    location: 'Remote',
    description: 'Contributed to open-source projects focused on improving frontend interactivity. Submitted PRs that enhanced UI responsiveness, fixed bugs, and refined user experience.',
    technologies: ['CSS', 'JavaScript'],
  },
];

export const sampleProjects = [
  {
    title: 'Landing Page Generator',
    description: 'An AI-powered landing page generator that creates high-converting landing pages using a Python CLI and Next.js frontend. Utilizes OpenAI API for content generation and offers multiple professional themes.',
    tech: ['Python Cli', 'Nextjs', 'OpenAI API'],
    screenshot: '/images/projects/ccux.png',
    liveLink: 'https://ccux.netlify.app/',
    codeLink: 'https://github.com/thisisharsh7/ccux',
  },
  {
    title: 'Git Playground',
    description: 'A platform build for beginners in Git commands. It consist of git commands visuals also an online playground for practicing for Git commands. I vibe codeed it',
    tech: ['AmazonQ', 'TailwindCSS', 'Next.js'],
    screenshot: '/images/projects/git-playground.png',
    liveLink: 'https://my-git-playground.vercel.app/',
    codeLink: 'https://github.com/thisisharsh7/git-playground',
  },
  {
    title: '30 Days of Code',
    description: 'A collection of beginner-friendly web projects built over 30 days without tutorials, demonstrating self-taught frontend skills.',
    tech: ['HTML', 'CSS', 'JavaScript', 'React'],
    screenshot: '/images/projects/30-days.png',
    liveLink: 'https://thisisharsh7.github.io/30-Days-of-code/',
    codeLink: 'https://github.com/thisisharsh7/30-Days-of-code',
  },
  {
    title: 'Clones Trio',
    description: 'A set of clones of real-world websites like Netflix, DigitalOcean, and Amazon, built using React and styled with TailwindCSS and plain CSS.',
    tech: ['React', 'Next.js', 'TailwindCSS'],
    screenshot: '/images/projects/clone-trio.png',
    liveLink: 'https://thisisharsh7.github.io/14-days-of-Clones/',
    codeLink: 'https://github.com/thisisharsh7/14-days-of-Clones',
  },
  {
    title: 'Hacker News',
    description: 'A news app built using the Hacker News API. Includes search functionality and the ability to view comment threads.',
    tech: ['React', 'TailwindCSS', 'API'],
    screenshot: '/images/projects/hacker-news.png',
    liveLink: 'https://yes-news.netlify.app/',
    codeLink: 'https://github.com/thisisharsh7/news-app',
  },
  {
    title: 'Dashboard UI',
    description: 'A sleek and responsive admin dashboard created with Next.js and TailwindCSS, ideal for visualizing and managing data.',
    tech: ['Next.js', 'TailwindCSS'],
    screenshot: '/images/projects/dash-board.png',
    liveLink: 'https://yes-dashboard.vercel.app/',
    codeLink: 'https://github.com/thisisharsh7/Dashboard-Ui',
  },
  {
    title: 'Story Generator App',
    description: 'A creative app that generates random stories based on user prompts using the OpenAI API, exploring AI-powered content generation.',
    tech: ['React', 'OpenAI API'],
    screenshot: '/images/projects/story-app.png',
    liveLink: '#',
    codeLink: 'https://github.com/thisisharsh7/story-app',
  },
  {
    title: 'React Chatbot',
    description: 'A secure chatbot built with React Chatbot Kit, featuring protected routes and styled with TailwindCSS.',
    tech: ['React', 'React Chatbot Kit', 'TailwindCSS'],
    screenshot: '/images/projects/chat-bot.png',
    liveLink: 'https://yes-chatbot.netlify.app/',
    codeLink: 'https://github.com/thisisharsh7/React-chatbot',
  },
  {
    title: 'Crater',
    description: 'A responsive dashboard designed for an AI-powered firm, built using React and styled with TailwindCSS.',
    tech: ['React', 'TailwindCSS'],
    screenshot: '/images/projects/crater-dash.png',
    liveLink: 'https://crater-ai.netlify.app/',
    codeLink: 'https://github.com/thisisharsh7/crater-assignment',
  }
];

// constants/preloadImages.js
export const preloadImageUrls = [
  // '/images/projects/my-shop.png',
  '/images/projects/30-days.png',
  '/images/projects/clone-trio.png',
  '/images/projects/hacker-news.png',
  '/images/projects/dash-board.png',
  '/images/projects/story-app.png',
  '/images/projects/git-playground.png',
  '/images/projects/chat-bot.png',
  '/images/projects/crater-dash.png',
  '/images/Harsh_Profile_Pic.jpg',
];
